"""add_hr_answer_kb_chunk_id_to_tickets

Revision ID: df1785a86345
Revises: 0003_auth_employees_tickets
Create Date: 2026-09-17 19:13:48.354148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'df1785a86345'
down_revision: Union[str, None] = '0003_auth_employees_tickets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chunk_embeddings_hnsw'), table_name='chunk_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chunk_embeddings_tenant_chunk'), table_name='chunk_embeddings')
    op.create_index(op.f('ix_chunk_embeddings_chunk_ref_id'), 'chunk_embeddings', ['chunk_ref_id'], unique=False)
    op.drop_index(op.f('ix_chunks_tenant_chunk'), table_name='chunks')
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_document_ref_id'), 'chunks', ['document_ref_id'], unique=False)
    op.add_column('tickets', sa.Column('hr_answer', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('kb_chunk_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_column('tickets', 'kb_chunk_id')
    op.drop_column('tickets', 'hr_answer')
    op.drop_index(op.f('ix_chunks_document_ref_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_tenant_chunk'), 'chunks', ['tenant_id', 'chunk_id'], unique=False)
    op.drop_index(op.f('ix_chunk_embeddings_chunk_ref_id'), table_name='chunk_embeddings')
    op.create_index(op.f('ix_chunk_embeddings_tenant_chunk'), 'chunk_embeddings', ['tenant_id', 'chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_hnsw'), 'chunk_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    # ### end Alembic commands ###
