"""Clarify Node — Module 5.

LangGraph node for when the employee's intent is too ambiguous to route.
Generates a polite clarification question and sets requires_clarification=True.
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict

try:
    from backend.app.agents.agent_state import AgentState
except ImportError:
    from app.agents.agent_state import AgentState

logger = logging.getLogger("agents.clarify_node")

# Default clarification when no LLM is available
_DEFAULT_CLARIFICATION = (
    "I'd like to help, but I'm not sure what you're looking for. "
    "Could you tell me more? For example, are you asking about a company policy, "
    "requesting IT support, or something else?"
)


class ClarifyNode:
    """
    LangGraph node: generates a clarification question when intent is ambiguous.

    If a custom_question is injected (e.g., from tests), it overrides the default.
    In production, a more context-aware question could be generated by an LLM —
    this is left as a Module 6 enhancement.
    """

    def __init__(self, custom_question: str = ""):
        self._custom_question = custom_question

    def __call__(self, state: AgentState) -> Dict[str, Any]:
        """Node callable — writes clarification question to state."""
        intent_reasoning = state.get("intent_reasoning", "")

        # Build a contextual clarification question
        if self._custom_question:
            question = self._custom_question
        else:
            question = _build_clarification_question(state.get("request", ""), intent_reasoning)

        logger.info("Clarify node triggered. Reasoning: %s", intent_reasoning)

        return {
            "agent_mode": "clarify",
            "requires_clarification": True,
            "clarification_question": question,
            "final_response": question,
        }


def _build_clarification_question(request: str, reasoning: str) -> str:
    """
    Builds a context-sensitive clarification question.
    Simple rule-based for now — LLM-enhanced in Module 6.
    """
    if not request or not request.strip():
        return _DEFAULT_CLARIFICATION

    return (
        f"I'd like to help with your request. Could you provide a bit more detail? "
        f"For example:\n"
        f"- Are you asking about a company policy or benefit?\n"
        f"- Do you need IT support or access to a system?\n"
        f"- Would you like to request leave, book a meeting, or something else?\n\n"
        f"The more specific you are, the better I can assist you."
    )
